apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # מזהה את ה-Pods שלך על פי ה-label 'app: nginx'
  ports:
    - protocol: TCP
      port: 80      # הפורט שבו ה-Service יהיה זמין
      targetPort: 80 # הפורט שבו ה-Nginx מאזין בתוך ה-Pod
  type: LoadBalancer # סוג ה-Service שייצור IP חיצוני
